# Generated by Django 5.2.1 on 2025-06-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilpymes',
            name='id_imagenes',
        ),
        migrations.RemoveField(
            model_name='perfilpymes',
            name='id_perfilRed',
        ),
    ]
