# Generated by Django 5.2.1 on 2025-06-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_seguidores_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pymes',
            name='carnet',
            field=models.ImageField(blank=True, null=True, upload_to='pymes/'),
        ),
    ]
