# Generated by Django 5.2.1 on 2025-06-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pymes_carnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pymes',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
    ]
