# Generated by Django 5.2.1 on 2025-07-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pymes_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenes',
            old_name='id_pyme',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='perfilpymes',
            old_name='id_pyme',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='perfilredes',
            old_name='id_pyme',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='publicaciones',
            old_name='id_pyme',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='seguidores',
            old_name='id_pyme',
            new_name='usuario',
        ),
    ]
