# Generated by Django 5.2.1 on 2025-07-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pymes_verificada_alter_pymes_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pymes',
            name='verificada',
        ),
    ]
