# Generated by Django 5.2.1 on 2025-06-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pymes_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pymes',
            name='descripcion',
            field=models.TextField(default='Especializado en queques', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pymes',
            name='direccion',
            field=models.CharField(default='Puntareas, Puntareanas', max_length=250),
            preserve_default=False,
        ),
    ]
